name: CI

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/ci.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.23', '1.24', '1.25' ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - run: go mod download
      - run: go vet ./...
      - uses: dominikh/staticcheck-action@v1
        with: { install-go: false }
      - run: go test -v ./...